export interface MockUser {
  id: string;
  name: string;
  role: 'Admin' | 'Data Manager' | 'Salesman' | 'Program Previewer';
  code: string;
  photoURL?: string;
  status: 'online' | 'offline';
  allowedPages?: string[];
}

export interface MockCustomer {
  id: string;
  name: string;
  phone: string;
  address: string;
}

export interface MockSupplier {
  id: string;
  supplierName: string;
  phoneNumber: string;
  address: string;
}

export interface MockProductDefinition {
  id: string;
  productName: string;
  category: 'Mattress' | 'Bed' | 'Pillow' | 'Cover';
  supplier: string;
  sizeModel: string;
  defaultPrice: number;
  discountPercent?: number;
}

export interface MockProduct {
  id: string;
  productName: string;
  category: 'Mattress' | 'Bed' | 'Pillow' | 'Cover';
  sizeModel: string;
  stockLocation: 'Warehouse' | 'Shop Showroom';
  currentQuantity: number;
  unitPrice: number;
  sellingPrice: number;
  supplierId: string;
}

export interface MockSellingFormProduct {
  id: string;
  formId: string;
  productId: string;
  productName: string;
  category: string;
  sizeModel?: string;
  quantity: number;
  unitPrice: number;
  purchasePrice?: number;
  lineTotal: number;
}

export interface MockPayment {
  id: string;
  formId: string;
  paymentDate: string;
  amountPaid: number;
  paymentMethod: 'Cash' | 'Transfer';
  note?: string;
}

export interface MockSellingForm {
  id: string;
  formNumber: string;
  customerName: string;
  customerId: string;
  customerPhoneNumber?: string;
  customerAddress?: string;
  issueDate: string;
  totalPrice: number;
  totalPaid: number;
  remainingBalance: number;
  paymentStatus: 'Fully Paid' | 'Partially Paid' | 'Unpaid';
  paymentType: 'Direct Payment' | 'After Delivery' | 'Installments' | 'Pre-order';
  creatorId: string;
  creatorName: string;
  deliveryCost?: number;
  discountType?: 'percentage' | 'cash';
  discountValue?: number;
}

export interface MockBuyingFormProduct {
  id: string;
  formId: string;
  productId: string;
  productName: string;
  category: string;
  quantity: number;
  unitPrice: number;
  lineTotal: number;
}

export interface MockBuyingForm {
  id: string;
  formNumber: string;
  supplierId: string;
  supplierName: string;
  issueDate: string;
  totalAmount: number;
  customsFee?: number;
  deliveryCost?: number;
  notes?: string;
}

export interface MockExpense {
  id: string;
  name: string;
  category: 'Daily' | 'Salary' | 'Rent' | 'Electricity' | 'Transport' | 'Other';
  amount: number;
  currency: 'USD' | 'IQD';
  date: string;
  paidBy?: 'Cash' | 'Transfer';
  notes?: string;
}

export interface MockStockMovement {
  id: string;
  productId: string;
  productName: string;
  fromLocation: 'Warehouse' | 'Shop Showroom';
  toLocation: 'Warehouse' | 'Shop Showroom';
  quantity: number;
  date: string;
  performedBy: string;
}

export const INITIAL_MOCK_DATA = {
  users: {
    'demo-admin': {
      id: 'demo-admin',
      name: 'پیشاندەر (Demo Admin)',
      role: 'Admin',
      code: '1234',
      photoURL: '',
      status: 'online',
      allowedPages: [
        '/dashboard',
        '/sales',
        '/purchases',
        '/stock',
        '/products',
        '/customers',
        '/suppliers',
        '/expenses',
        '/tutorial',
        '/settings',
      ],
    },
    'demo-datamanager': {
      id: 'demo-datamanager',
      name: 'سەرپەرشتیاری داتا (Data Manager)',
      role: 'Data Manager',
      code: '2222',
      status: 'online',
      allowedPages: [
        '/dashboard',
        '/sales',
        '/purchases',
        '/stock',
        '/products',
        '/customers',
        '/suppliers',
        '/expenses',
        '/tutorial',
        '/settings',
      ],
    },
    'demo-salesman': {
      id: 'demo-salesman',
      name: 'فرۆشیاری پێشاندان (Salesman)',
      role: 'Salesman',
      code: '3333',
      status: 'offline',
      allowedPages: ['/sales', '/customers', '/stock', '/tutorial'],
    },
  },

  suppliers: {
    'sup-1': {
      id: 'sup-1',
      supplierName: 'بێدئاڕت (BedArt)',
      phoneNumber: '07703071818',
      address: 'سلێمانی - ناوچەی پیشەسازی',
    },
    'sup-2': {
      id: 'sup-2',
      supplierName: 'ئارمیس (Armis)',
      phoneNumber: '07501122334',
      address: 'تورکیا - ئیستەنبوڵ',
    },
    'sup-3': {
      id: 'sup-3',
      supplierName: 'ڤیسکۆ تێکس (ViscoTex)',
      phoneNumber: '07719988776',
      address: 'ئیتاڵیا - میلان',
    },
    'sup-4': {
      id: 'sup-4',
      supplierName: 'بێد ئاند سلیپ (Bed & Sleep)',
      phoneNumber: '07705544332',
      address: 'هەولێر - شۆڕش',
    },
    'sup-5': {
      id: 'sup-5',
      supplierName: 'یاتاش بێدینگ (Yatas)',
      phoneNumber: '07503344556',
      address: 'تورکیا - قەیسەری',
    },
    'sup-6': {
      id: 'sup-6',
      supplierName: 'لۆکە هۆم (Loka Home)',
      phoneNumber: '07721122334',
      address: 'سلێمانی - ڕاپەڕین',
    },
    'sup-7': {
      id: 'sup-7',
      supplierName: 'ئیبراهیم تێک (Ibrahim Tech)',
      phoneNumber: '07709876543',
      address: 'سلێمانی - عەربەت',
    },
  },

  customers: {
    'cust-1': {
      id: 'cust-1',
      name: 'ئاراس محەمەد کەریم',
      phone: '07701234567',
      address: 'سلێمانی - قەیوان ستی',
    },
    'cust-2': {
      id: 'cust-2',
      name: 'دالیا ئەحمەد ڕەسوڵ',
      phone: '07711145340',
      address: 'سلێمانی - بەختیاری',
    },
    'cust-3': {
      id: 'cust-3',
      name: 'سەفین کەمال والی',
      phone: '07501140810',
      address: 'هەولێر - وەزیران',
    },
    'cust-4': {
      id: 'cust-4',
      name: 'سۆما ئاوات حەمید',
      phone: '07700571105',
      address: 'سلێمانی - تووی مەلیک',
    },
    'cust-5': {
      id: 'cust-5',
      name: 'د. کامەران فەریق',
      phone: '07703600335',
      address: 'سلێمانی - گاردن ستی',
    },
    'cust-6': {
      id: 'cust-6',
      name: 'تارا حسێن تەییب',
      phone: '07701503577',
      address: 'سلێمانی - شاری سپی',
    },
    'cust-7': {
      id: 'cust-7',
      name: 'کاروان نەوزاد بەکر',
      phone: '07701526262',
      address: 'هەولێر - گوندی ئیتاڵی',
    },
    'cust-8': {
      id: 'cust-8',
      name: 'شەیما مەحموود تاهیر',
      phone: '07701528797',
      address: 'ڕانیە - ڕزگاری',
    },
    'cust-9': {
      id: 'cust-9',
      name: 'سۆران بەختیار قادر',
      phone: '07701572949',
      address: 'سلێمانی - چوارچرا',
    },
    'cust-10': {
      id: 'cust-10',
      name: 'شنۆ جەلال عەبدوڵڵا',
      phone: '07736984336',
      address: 'سلێمانی - سالم',
    },
    'cust-11': {
      id: 'cust-11',
      name: 'بێستوون ئەکرەم فەرەج',
      phone: '07701548555',
      address: 'سلێمانی - شەکرەکە',
    },
    'cust-12': {
      id: 'cust-12',
      name: 'ڕزگار عەبدوڵڵا مەعروف',
      phone: '07701529152',
      address: 'سلێمانی - دانیا ستی',
    },
    'cust-13': {
      id: 'cust-13',
      name: 'هێمن جەمال تۆفیق',
      phone: '07501445566',
      address: 'سلێمانی - سەرچنار',
    },
    'cust-14': {
      id: 'cust-14',
      name: 'ڕۆژان کەریم قادر',
      phone: '07704561234',
      address: 'هەولێر - ئەسکانی',
    },
    'cust-15': {
      id: 'cust-15',
      name: 'لوقمان حسێن مەحموود',
      phone: '07718901234',
      address: 'دهۆک - سەنتەری شار',
    },
  },

  product_definitions: {
    'pdef-1': {
      id: 'pdef-1',
      productName: 'دۆشەکی ئۆسکار١٨٠*٢',
      category: 'Mattress',
      sizeModel: '180*2',
      supplier: 'بێدئاڕت (BedArt)',
      defaultPrice: 280,
      discountPercent: 10,
    },
    'pdef-2': {
      id: 'pdef-2',
      productName: 'دۆشەکی ئۆپتیمەم ٩٠*١٩٠',
      category: 'Mattress',
      sizeModel: '90*190',
      supplier: 'ئارمیس (Armis)',
      defaultPrice: 150,
      discountPercent: 10,
    },
    'pdef-3': {
      id: 'pdef-3',
      productName: 'دۆشەکی ئیسکەلەید ١٨٠*٢',
      category: 'Mattress',
      sizeModel: '180*2',
      supplier: 'ئارمیس (Armis)',
      defaultPrice: 340,
      discountPercent: 10,
    },
    'pdef-4': {
      id: 'pdef-4',
      productName: 'دۆشەکی ئینفینیتی١٦٠*٢',
      category: 'Mattress',
      sizeModel: '160*2',
      supplier: 'بێدئاڕت (BedArt)',
      defaultPrice: 300,
      discountPercent: 10,
    },
    'pdef-5': {
      id: 'pdef-5',
      productName: 'دۆشەکی ئەلیگرۆ١٨٠*٢',
      category: 'Mattress',
      sizeModel: '180*2',
      supplier: 'بێدئاڕت (BedArt)',
      defaultPrice: 250,
      discountPercent: 10,
    },
    'pdef-6': {
      id: 'pdef-6',
      productName: 'دۆشەکی کلاودس ١٨٠*٢',
      category: 'Mattress',
      sizeModel: '180*2',
      supplier: 'ڤیسکۆ تێکس (ViscoTex)',
      defaultPrice: 390,
      discountPercent: 10,
    },
    'pdef-7': {
      id: 'pdef-7',
      productName: 'دۆشەکی سویس کوین ٢*٢',
      category: 'Mattress',
      sizeModel: '200*200',
      supplier: 'بێد ئاند سلیپ (Bed & Sleep)',
      defaultPrice: 420,
      discountPercent: 10,
    },
    'pdef-8': {
      id: 'pdef-8',
      productName: 'سێتی تەختی میلۆدی 180*2',
      category: 'Bed',
      sizeModel: '180*2',
      supplier: 'بێد ئاند سلیپ (Bed & Sleep)',
      defaultPrice: 720,
      discountPercent: 10,
    },
    'pdef-9': {
      id: 'pdef-9',
      productName: 'سێتی تەختی دایمۆند 180*2',
      category: 'Bed',
      sizeModel: '180*2',
      supplier: 'بێد ئاند سلیپ (Bed & Sleep)',
      defaultPrice: 850,
      discountPercent: 10,
    },
    'pdef-10': {
      id: 'pdef-10',
      productName: 'سێتی تەختی کوینلاند١٨٠*٢',
      category: 'Bed',
      sizeModel: '180*2',
      supplier: 'بێدئاڕت (BedArt)',
      defaultPrice: 600,
      discountPercent: 10,
    },
    'pdef-11': {
      id: 'pdef-11',
      productName: 'سێتی تەختی سێرمۆ کەلەر ٢*٢',
      category: 'Bed',
      sizeModel: '200*200',
      supplier: 'یاتاش بێدینگ (Yatas)',
      defaultPrice: 900,
      discountPercent: 10,
    },
    'pdef-12': {
      id: 'pdef-12',
      productName: 'سەرینی پشتی ڤیسکۆ L ٦٠*٣٨*١٠',
      category: 'Pillow',
      sizeModel: '60*38*10',
      supplier: 'ڤیسکۆ تێکس (ViscoTex)',
      defaultPrice: 35,
      discountPercent: 10,
    },
    'pdef-13': {
      id: 'pdef-13',
      productName: 'سەرینی تەندروستی پریمۆ',
      category: 'Pillow',
      sizeModel: 'Standard',
      supplier: 'یاتاش بێدینگ (Yatas)',
      defaultPrice: 40,
      discountPercent: 10,
    },
    'pdef-14': {
      id: 'pdef-14',
      productName: 'بەرگی دۆشەکی لۆکە هۆم ١٨٠*٢',
      category: 'Cover',
      sizeModel: '180*2',
      supplier: 'لۆکە هۆم (Loka Home)',
      defaultPrice: 28,
      discountPercent: 10,
    },
    'pdef-15': {
      id: 'pdef-15',
      productName: 'بەرگی دۆشەکی ئاو نەبڕ ١٦٠*٢',
      category: 'Cover',
      sizeModel: '160*2',
      supplier: 'بێدئاڕت (BedArt)',
      defaultPrice: 32,
      discountPercent: 10,
    },
  },

  products: {
    'prod-1-wh': {
      id: 'prod-1-wh',
      productName: 'دۆشەکی ئۆسکار١٨٠*٢',
      category: 'Mattress',
      sizeModel: '180*2',
      stockLocation: 'Warehouse',
      currentQuantity: 12,
      unitPrice: 180,
      sellingPrice: 280,
      supplierId: 'sup-1',
    },
    'prod-1-sh': {
      id: 'prod-1-sh',
      productName: 'دۆشەکی ئۆسکار١٨٠*٢',
      category: 'Mattress',
      sizeModel: '180*2',
      stockLocation: 'Shop Showroom',
      currentQuantity: 3,
      unitPrice: 180,
      sellingPrice: 280,
      supplierId: 'sup-1',
    },
    'prod-2-wh': {
      id: 'prod-2-wh',
      productName: 'دۆشەکی ئۆپتیمەم ٩٠*١٩٠',
      category: 'Mattress',
      sizeModel: '90*190',
      stockLocation: 'Warehouse',
      currentQuantity: 8,
      unitPrice: 95,
      sellingPrice: 150,
      supplierId: 'sup-2',
    },
    'prod-2-sh': {
      id: 'prod-2-sh',
      productName: 'دۆشەکی ئۆپتیمەم ٩٠*١٩٠',
      category: 'Mattress',
      sizeModel: '90*190',
      stockLocation: 'Shop Showroom',
      currentQuantity: 2,
      unitPrice: 95,
      sellingPrice: 150,
      supplierId: 'sup-2',
    },
    'prod-3-wh': {
      id: 'prod-3-wh',
      productName: 'دۆشەکی ئیسکەلەید ١٨٠*٢',
      category: 'Mattress',
      sizeModel: '180*2',
      stockLocation: 'Warehouse',
      currentQuantity: 15,
      unitPrice: 220,
      sellingPrice: 340,
      supplierId: 'sup-2',
    },
    'prod-3-sh': {
      id: 'prod-3-sh',
      productName: 'دۆشەکی ئیسکەلەید ١٨٠*٢',
      category: 'Mattress',
      sizeModel: '180*2',
      stockLocation: 'Shop Showroom',
      currentQuantity: 4,
      unitPrice: 220,
      sellingPrice: 340,
      supplierId: 'sup-2',
    },
    'prod-4-wh': {
      id: 'prod-4-wh',
      productName: 'دۆشەکی ئینفینیتی١٦٠*٢',
      category: 'Mattress',
      sizeModel: '160*2',
      stockLocation: 'Warehouse',
      currentQuantity: 14,
      unitPrice: 190,
      sellingPrice: 300,
      supplierId: 'sup-1',
    },
    'prod-4-sh': {
      id: 'prod-4-sh',
      productName: 'دۆشەکی ئینفینیتی١٦٠*٢',
      category: 'Mattress',
      sizeModel: '160*2',
      stockLocation: 'Shop Showroom',
      currentQuantity: 3,
      unitPrice: 190,
      sellingPrice: 300,
      supplierId: 'sup-1',
    },
    'prod-5-wh': {
      id: 'prod-5-wh',
      productName: 'دۆشەکی ئەلیگرۆ١٨٠*٢',
      category: 'Mattress',
      sizeModel: '180*2',
      stockLocation: 'Warehouse',
      currentQuantity: 18,
      unitPrice: 160,
      sellingPrice: 250,
      supplierId: 'sup-1',
    },
    'prod-5-sh': {
      id: 'prod-5-sh',
      productName: 'دۆشەکی ئەلیگرۆ١٨٠*٢',
      category: 'Mattress',
      sizeModel: '180*2',
      stockLocation: 'Shop Showroom',
      currentQuantity: 5,
      unitPrice: 160,
      sellingPrice: 250,
      supplierId: 'sup-1',
    },
    'prod-6-wh': {
      id: 'prod-6-wh',
      productName: 'دۆشەکی کلاودس ١٨٠*٢',
      category: 'Mattress',
      sizeModel: '180*2',
      stockLocation: 'Warehouse',
      currentQuantity: 2,
      unitPrice: 250,
      sellingPrice: 390,
      supplierId: 'sup-3',
    },
    'prod-6-sh': {
      id: 'prod-6-sh',
      productName: 'دۆشەکی کلاودس ١٨٠*٢',
      category: 'Mattress',
      sizeModel: '180*2',
      stockLocation: 'Shop Showroom',
      currentQuantity: 1,
      unitPrice: 250,
      sellingPrice: 390,
      supplierId: 'sup-3',
    },
    'prod-7-wh': {
      id: 'prod-7-wh',
      productName: 'دۆشەکی سویس کوین ٢*٢',
      category: 'Mattress',
      sizeModel: '200*200',
      stockLocation: 'Warehouse',
      currentQuantity: 6,
      unitPrice: 270,
      sellingPrice: 420,
      supplierId: 'sup-4',
    },
    'prod-7-sh': {
      id: 'prod-7-sh',
      productName: 'دۆشەکی سویس کوین ٢*٢',
      category: 'Mattress',
      sizeModel: '200*200',
      stockLocation: 'Shop Showroom',
      currentQuantity: 2,
      unitPrice: 270,
      sellingPrice: 420,
      supplierId: 'sup-4',
    },
    'prod-8-wh': {
      id: 'prod-8-wh',
      productName: 'سێتی تەختی میلۆدی 180*2',
      category: 'Bed',
      sizeModel: '180*2',
      stockLocation: 'Warehouse',
      currentQuantity: 6,
      unitPrice: 450,
      sellingPrice: 720,
      supplierId: 'sup-4',
    },
    'prod-8-sh': {
      id: 'prod-8-sh',
      productName: 'سێتی تەختی میلۆدی 180*2',
      category: 'Bed',
      sizeModel: '180*2',
      stockLocation: 'Shop Showroom',
      currentQuantity: 2,
      unitPrice: 450,
      sellingPrice: 720,
      supplierId: 'sup-4',
    },
    'prod-9-wh': {
      id: 'prod-9-wh',
      productName: 'سێتی تەختی دایمۆند 180*2',
      category: 'Bed',
      sizeModel: '180*2',
      stockLocation: 'Warehouse',
      currentQuantity: 4,
      unitPrice: 520,
      sellingPrice: 850,
      supplierId: 'sup-4',
    },
    'prod-9-sh': {
      id: 'prod-9-sh',
      productName: 'سێتی تەختی دایمۆند 180*2',
      category: 'Bed',
      sizeModel: '180*2',
      stockLocation: 'Shop Showroom',
      currentQuantity: 1,
      unitPrice: 520,
      sellingPrice: 850,
      supplierId: 'sup-4',
    },
    'prod-10-wh': {
      id: 'prod-10-wh',
      productName: 'سێتی تەختی کوینلاند١٨٠*٢',
      category: 'Bed',
      sizeModel: '180*2',
      stockLocation: 'Warehouse',
      currentQuantity: 2,
      unitPrice: 380,
      sellingPrice: 600,
      supplierId: 'sup-1',
    },
    'prod-10-sh': {
      id: 'prod-10-sh',
      productName: 'سێتی تەختی کوینلاند١٨٠*٢',
      category: 'Bed',
      sizeModel: '180*2',
      stockLocation: 'Shop Showroom',
      currentQuantity: 1,
      unitPrice: 380,
      sellingPrice: 600,
      supplierId: 'sup-1',
    },
    'prod-11-wh': {
      id: 'prod-11-wh',
      productName: 'سەرینی پشتی ڤیسکۆ L ٦٠*٣٨*١٠',
      category: 'Pillow',
      sizeModel: '60*38*10',
      stockLocation: 'Warehouse',
      currentQuantity: 40,
      unitPrice: 18,
      sellingPrice: 35,
      supplierId: 'sup-3',
    },
    'prod-11-sh': {
      id: 'prod-11-sh',
      productName: 'سەرینی پشتی ڤیسکۆ L ٦٠*٣٨*١٠',
      category: 'Pillow',
      sizeModel: '60*38*10',
      stockLocation: 'Shop Showroom',
      currentQuantity: 12,
      unitPrice: 18,
      sellingPrice: 35,
      supplierId: 'sup-3',
    },
    'prod-12-wh': {
      id: 'prod-12-wh',
      productName: 'سەرینی تەندروستی پریمۆ',
      category: 'Pillow',
      sizeModel: 'Standard',
      stockLocation: 'Warehouse',
      currentQuantity: 25,
      unitPrice: 22,
      sellingPrice: 40,
      supplierId: 'sup-5',
    },
    'prod-12-sh': {
      id: 'prod-12-sh',
      productName: 'سەرینی تەندروستی پریمۆ',
      category: 'Pillow',
      sizeModel: 'Standard',
      stockLocation: 'Shop Showroom',
      currentQuantity: 8,
      unitPrice: 22,
      sellingPrice: 40,
      supplierId: 'sup-5',
    },
    'prod-13-wh': {
      id: 'prod-13-wh',
      productName: 'بەرگی دۆشەکی لۆکە هۆم ١٨٠*٢',
      category: 'Cover',
      sizeModel: '180*2',
      stockLocation: 'Warehouse',
      currentQuantity: 35,
      unitPrice: 14,
      sellingPrice: 28,
      supplierId: 'sup-6',
    },
    'prod-13-sh': {
      id: 'prod-13-sh',
      productName: 'بەرگی دۆشەکی لۆکە هۆم ١٨٠*٢',
      category: 'Cover',
      sizeModel: '180*2',
      stockLocation: 'Shop Showroom',
      currentQuantity: 10,
      unitPrice: 14,
      sellingPrice: 28,
      supplierId: 'sup-6',
    },
    'prod-14-wh': {
      id: 'prod-14-wh',
      productName: 'بەرگی دۆشەکی ئاو نەبڕ ١٦٠*٢',
      category: 'Cover',
      sizeModel: '160*2',
      stockLocation: 'Warehouse',
      currentQuantity: 30,
      unitPrice: 16,
      sellingPrice: 32,
      supplierId: 'sup-1',
    },
    'prod-14-sh': {
      id: 'prod-14-sh',
      productName: 'بەرگی دۆشەکی ئاو نەبڕ ١٦٠*٢',
      category: 'Cover',
      sizeModel: '160*2',
      stockLocation: 'Shop Showroom',
      currentQuantity: 7,
      unitPrice: 16,
      sellingPrice: 32,
      supplierId: 'sup-1',
    },
  },

  selling_forms: {
    'sf-101': {
      id: 'sf-101',
      formNumber: 'SF-1001',
      customerName: 'ئاراس محەمەد کەریم',
      customerId: 'cust-1',
      customerPhoneNumber: '07701234567',
      customerAddress: 'سلێمانی - قەیوان ستی',
      issueDate: '2026-09-24',
      totalPrice: 560,
      totalPaid: 560,
      remainingBalance: 0,
      paymentStatus: 'Fully Paid',
      paymentType: 'Direct Payment',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
      deliveryCost: 0,
      discountType: 'cash',
      discountValue: 0,
    },
    'sf-102': {
      id: 'sf-102',
      formNumber: 'SF-1002',
      customerName: 'دالیا ئەحمەد ڕەسوڵ',
      customerId: 'cust-2',
      customerPhoneNumber: '07711145340',
      customerAddress: 'سلێمانی - بەختیاری',
      issueDate: '2026-09-22',
      totalPrice: 1040,
      totalPaid: 600,
      remainingBalance: 440,
      paymentStatus: 'Partially Paid',
      paymentType: 'Installments',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
      deliveryCost: 20,
      discountType: 'percentage',
      discountValue: 5,
    },
    'sf-103': {
      id: 'sf-103',
      formNumber: 'SF-1003',
      customerName: 'سەفین کەمال والی',
      customerId: 'cust-3',
      customerPhoneNumber: '07501140810',
      customerAddress: 'هەولێر - وەزیران',
      issueDate: '2026-09-18',
      totalPrice: 850,
      totalPaid: 850,
      remainingBalance: 0,
      paymentStatus: 'Fully Paid',
      paymentType: 'Direct Payment',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
    },
    'sf-104': {
      id: 'sf-104',
      formNumber: 'SF-1004',
      customerName: 'سۆما ئاوات حەمید',
      customerId: 'cust-4',
      customerPhoneNumber: '07700571105',
      customerAddress: 'سلێمانی - تووی مەلیک',
      issueDate: '2026-09-15',
      totalPrice: 380,
      totalPaid: 0,
      remainingBalance: 380,
      paymentStatus: 'Unpaid',
      paymentType: 'After Delivery',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
    },
    'sf-105': {
      id: 'sf-105',
      formNumber: 'SF-1005',
      customerName: 'د. کامەران فەریق',
      customerId: 'cust-5',
      customerPhoneNumber: '07703600335',
      customerAddress: 'سلێمانی - گاردن ستی',
      issueDate: '2026-09-11',
      totalPrice: 1470,
      totalPaid: 1470,
      remainingBalance: 0,
      paymentStatus: 'Fully Paid',
      paymentType: 'Direct Payment',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
    },
    'sf-106': {
      id: 'sf-106',
      formNumber: 'SF-1006',
      customerName: 'تارا حسێن تەییب',
      customerId: 'cust-6',
      customerPhoneNumber: '07701503577',
      customerAddress: 'سلێمانی - شاری سپی',
      issueDate: '2026-09-08',
      totalPrice: 420,
      totalPaid: 420,
      remainingBalance: 0,
      paymentStatus: 'Fully Paid',
      paymentType: 'Direct Payment',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
    },
    'sf-107': {
      id: 'sf-107',
      formNumber: 'SF-1007',
      customerName: 'کاروان نەوزاد بەکر',
      customerId: 'cust-7',
      customerPhoneNumber: '07701526262',
      customerAddress: 'هەولێر - گوندی ئیتاڵی',
      issueDate: '2026-09-04',
      totalPrice: 1950,
      totalPaid: 1000,
      remainingBalance: 950,
      paymentStatus: 'Partially Paid',
      paymentType: 'Installments',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
    },
    'sf-108': {
      id: 'sf-108',
      formNumber: 'SF-1008',
      customerName: 'شەیما مەحموود تاهیر',
      customerId: 'cust-8',
      customerPhoneNumber: '07701528797',
      customerAddress: 'ڕانیە - ڕزگاری',
      issueDate: '2026-08-28',
      totalPrice: 720,
      totalPaid: 720,
      remainingBalance: 0,
      paymentStatus: 'Fully Paid',
      paymentType: 'Direct Payment',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
    },
    'sf-109': {
      id: 'sf-109',
      formNumber: 'SF-1009',
      customerName: 'سۆران بەختیار قادر',
      customerId: 'cust-9',
      customerPhoneNumber: '07701572949',
      customerAddress: 'سلێمانی - چوارچرا',
      issueDate: '2026-08-20',
      totalPrice: 340,
      totalPaid: 340,
      remainingBalance: 0,
      paymentStatus: 'Fully Paid',
      paymentType: 'Direct Payment',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
    },
    'sf-110': {
      id: 'sf-110',
      formNumber: 'SF-1010',
      customerName: 'شنۆ جەلال عەبدوڵڵا',
      customerId: 'cust-10',
      customerPhoneNumber: '07736984336',
      customerAddress: 'سلێمانی - سالم',
      issueDate: '2026-08-14',
      totalPrice: 600,
      totalPaid: 600,
      remainingBalance: 0,
      paymentStatus: 'Fully Paid',
      paymentType: 'Direct Payment',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
    },
    'sf-111': {
      id: 'sf-111',
      formNumber: 'SF-1011',
      customerName: 'بێستوون ئەکرەم فەرەج',
      customerId: 'cust-11',
      customerPhoneNumber: '07701548555',
      customerAddress: 'سلێمانی - شەکرەکە',
      issueDate: '2026-08-05',
      totalPrice: 900,
      totalPaid: 900,
      remainingBalance: 0,
      paymentStatus: 'Fully Paid',
      paymentType: 'Direct Payment',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
    },
    'sf-112': {
      id: 'sf-112',
      formNumber: 'SF-1012',
      customerName: 'ڕزگار عەبدوڵڵا مەعروف',
      customerId: 'cust-12',
      customerPhoneNumber: '07701529152',
      customerAddress: 'سلێمانی - دانیا ستی',
      issueDate: '2026-07-26',
      totalPrice: 420,
      totalPaid: 420,
      remainingBalance: 0,
      paymentStatus: 'Fully Paid',
      paymentType: 'Direct Payment',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
    },
    'sf-113': {
      id: 'sf-113',
      formNumber: 'SF-1013',
      customerName: 'هێمن جەمال تۆفیق',
      customerId: 'cust-13',
      customerPhoneNumber: '07501445566',
      customerAddress: 'سلێمانی - سەرچنار',
      issueDate: '2026-07-15',
      totalPrice: 1200,
      totalPaid: 1200,
      remainingBalance: 0,
      paymentStatus: 'Fully Paid',
      paymentType: 'Direct Payment',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
    },
    'sf-114': {
      id: 'sf-114',
      formNumber: 'SF-1014',
      customerName: 'ڕۆژان کەریم قادر',
      customerId: 'cust-14',
      customerPhoneNumber: '07704561234',
      customerAddress: 'هەولێر - ئەسکانی',
      issueDate: '2026-06-25',
      totalPrice: 680,
      totalPaid: 680,
      remainingBalance: 0,
      paymentStatus: 'Fully Paid',
      paymentType: 'Direct Payment',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
    },
    'sf-115': {
      id: 'sf-115',
      formNumber: 'SF-1015',
      customerName: 'لوقمان حسێن مەحموود',
      customerId: 'cust-15',
      customerPhoneNumber: '07718901234',
      customerAddress: 'دهۆک - سەنتەری شار',
      issueDate: '2026-06-10',
      totalPrice: 850,
      totalPaid: 850,
      remainingBalance: 0,
      paymentStatus: 'Fully Paid',
      paymentType: 'Direct Payment',
      creatorId: 'demo-admin',
      creatorName: 'پیشاندەر (Demo Admin)',
    },
  },

  // Subcollections for selling forms
  selling_form_products: {
    'sf-101/p-1': {
      id: 'p-1',
      formId: 'sf-101',
      productId: 'prod-1-sh',
      productName: 'دۆشەکی ئۆسکار١٨٠*٢',
      category: 'Mattress',
      quantity: 2,
      unitPrice: 280,
      purchasePrice: 180,
      lineTotal: 560,
    },
    'sf-102/p-1': {
      id: 'p-1',
      formId: 'sf-102',
      productId: 'prod-8-sh',
      productName: 'سێتی تەختی میلۆدی 180*2',
      category: 'Bed',
      quantity: 1,
      unitPrice: 720,
      purchasePrice: 450,
      lineTotal: 720,
    },
    'sf-102/p-2': {
      id: 'p-2',
      formId: 'sf-102',
      productId: 'prod-4-sh',
      productName: 'دۆشەکی ئینفینیتی١٦٠*٢',
      category: 'Mattress',
      quantity: 1,
      unitPrice: 300,
      purchasePrice: 190,
      lineTotal: 300,
    },
    'sf-103/p-1': {
      id: 'p-1',
      formId: 'sf-103',
      productId: 'prod-9-sh',
      productName: 'سێتی تەختی دایمۆند 180*2',
      category: 'Bed',
      quantity: 1,
      unitPrice: 850,
      purchasePrice: 520,
      lineTotal: 850,
    },
    'sf-104/p-1': {
      id: 'p-1',
      formId: 'sf-104',
      productId: 'prod-6-sh',
      productName: 'دۆشەکی کلاودس ١٨٠*٢',
      category: 'Mattress',
      quantity: 1,
      unitPrice: 380,
      purchasePrice: 250,
      lineTotal: 380,
    },
    'sf-105/p-1': {
      id: 'p-1',
      formId: 'sf-105',
      productId: 'prod-8-sh',
      productName: 'سێتی تەختی میلۆدی 180*2',
      category: 'Bed',
      quantity: 1,
      unitPrice: 720,
      purchasePrice: 450,
      lineTotal: 720,
    },
    'sf-105/p-2': {
      id: 'p-2',
      formId: 'sf-105',
      productId: 'prod-7-sh',
      productName: 'دۆشەکی سویس کوین ٢*٢',
      category: 'Mattress',
      quantity: 1,
      unitPrice: 420,
      purchasePrice: 270,
      lineTotal: 420,
    },
    'sf-105/p-3': {
      id: 'p-3',
      formId: 'sf-105',
      productId: 'prod-11-sh',
      productName: 'سەرینی پشتی ڤیسکۆ L ٦٠*٣٨*١٠',
      category: 'Pillow',
      quantity: 4,
      unitPrice: 35,
      purchasePrice: 18,
      lineTotal: 140,
    },
    'sf-106/p-1': {
      id: 'p-1',
      formId: 'sf-106',
      productId: 'prod-7-sh',
      productName: 'دۆشەکی سویس کوین ٢*٢',
      category: 'Mattress',
      quantity: 1,
      unitPrice: 420,
      purchasePrice: 270,
      lineTotal: 420,
    },
    'sf-107/p-1': {
      id: 'p-1',
      formId: 'sf-107',
      productId: 'prod-9-sh',
      productName: 'سێتی تەختی دایمۆند 180*2',
      category: 'Bed',
      quantity: 2,
      unitPrice: 850,
      purchasePrice: 520,
      lineTotal: 1700,
    },
    'sf-107/p-2': {
      id: 'p-2',
      formId: 'sf-107',
      productId: 'prod-5-sh',
      productName: 'دۆشەکی ئەلیگرۆ١٨٠*٢',
      category: 'Mattress',
      quantity: 1,
      unitPrice: 250,
      purchasePrice: 160,
      lineTotal: 250,
    },
    'sf-108/p-1': {
      id: 'p-1',
      formId: 'sf-108',
      productId: 'prod-8-sh',
      productName: 'سێتی تەختی میلۆدی 180*2',
      category: 'Bed',
      quantity: 1,
      unitPrice: 720,
      purchasePrice: 450,
      lineTotal: 720,
    },
    'sf-109/p-1': {
      id: 'p-1',
      formId: 'sf-109',
      productId: 'prod-3-sh',
      productName: 'دۆشەکی ئیسکەلەید ١٨٠*٢',
      category: 'Mattress',
      quantity: 1,
      unitPrice: 340,
      purchasePrice: 220,
      lineTotal: 340,
    },
    'sf-110/p-1': {
      id: 'p-1',
      formId: 'sf-110',
      productId: 'prod-10-sh',
      productName: 'سێتی تەختی کوینلاند١٨٠*٢',
      category: 'Bed',
      quantity: 1,
      unitPrice: 600,
      purchasePrice: 380,
      lineTotal: 600,
    },
    'sf-111/p-1': {
      id: 'p-1',
      formId: 'sf-111',
      productId: 'prod-1-sh',
      productName: 'دۆشەکی ئۆسکار١٨٠*٢',
      category: 'Mattress',
      quantity: 3,
      unitPrice: 280,
      purchasePrice: 180,
      lineTotal: 840,
    },
    'sf-112/p-1': {
      id: 'p-1',
      formId: 'sf-112',
      productId: 'prod-7-sh',
      productName: 'دۆشەکی سویس کوین ٢*٢',
      category: 'Mattress',
      quantity: 1,
      unitPrice: 420,
      purchasePrice: 270,
      lineTotal: 420,
    },
    'sf-113/p-1': {
      id: 'p-1',
      formId: 'sf-113',
      productId: 'prod-10-sh',
      productName: 'سێتی تەختی کوینلاند١٨٠*٢',
      category: 'Bed',
      quantity: 2,
      unitPrice: 600,
      purchasePrice: 380,
      lineTotal: 1200,
    },
    'sf-114/p-1': {
      id: 'p-1',
      formId: 'sf-114',
      productId: 'prod-3-sh',
      productName: 'دۆشەکی ئیسکەلەید ١٨٠*٢',
      category: 'Mattress',
      quantity: 2,
      unitPrice: 340,
      purchasePrice: 220,
      lineTotal: 680,
    },
    'sf-115/p-1': {
      id: 'p-1',
      formId: 'sf-115',
      productId: 'prod-9-sh',
      productName: 'سێتی تەختی دایمۆند 180*2',
      category: 'Bed',
      quantity: 1,
      unitPrice: 850,
      purchasePrice: 520,
      lineTotal: 850,
    },
  },

  payments: {
    'sf-101/pay-1': {
      id: 'pay-1',
      formId: 'sf-101',
      paymentDate: '2026-09-24',
      amountPaid: 560,
      paymentMethod: 'Cash',
      note: 'پارەی تەواو لە کاتی وەرگرتن',
    },
    'sf-102/pay-1': {
      id: 'pay-1',
      formId: 'sf-102',
      paymentDate: '2026-09-22',
      amountPaid: 600,
      paymentMethod: 'Transfer',
      note: 'پێشەکی قیست',
    },
    'sf-103/pay-1': {
      id: 'pay-1',
      formId: 'sf-103',
      paymentDate: '2026-09-18',
      amountPaid: 850,
      paymentMethod: 'Cash',
      note: 'کاش',
    },
    'sf-105/pay-1': {
      id: 'pay-1',
      formId: 'sf-105',
      paymentDate: '2026-09-11',
      amountPaid: 1470,
      paymentMethod: 'Cash',
      note: 'پارەی تەواو دراوە',
    },
    'sf-106/pay-1': {
      id: 'pay-1',
      formId: 'sf-106',
      paymentDate: '2026-09-08',
      amountPaid: 420,
      paymentMethod: 'Cash',
      note: 'کاش',
    },
    'sf-107/pay-1': {
      id: 'pay-1',
      formId: 'sf-107',
      paymentDate: '2026-09-04',
      amountPaid: 1000,
      paymentMethod: 'Transfer',
      note: 'قیستی یەکەم',
    },
    'sf-108/pay-1': {
      id: 'pay-1',
      formId: 'sf-108',
      paymentDate: '2026-08-28',
      amountPaid: 720,
      paymentMethod: 'Cash',
      note: 'کاش',
    },
    'sf-109/pay-1': {
      id: 'pay-1',
      formId: 'sf-109',
      paymentDate: '2026-08-20',
      amountPaid: 340,
      paymentMethod: 'Cash',
      note: 'کاش',
    },
    'sf-110/pay-1': {
      id: 'pay-1',
      formId: 'sf-110',
      paymentDate: '2026-08-14',
      amountPaid: 600,
      paymentMethod: 'Transfer',
      note: 'حەواڵە',
    },
    'sf-111/pay-1': {
      id: 'pay-1',
      formId: 'sf-111',
      paymentDate: '2026-08-05',
      amountPaid: 900,
      paymentMethod: 'Cash',
      note: 'کاش',
    },
    'sf-112/pay-1': {
      id: 'pay-1',
      formId: 'sf-112',
      paymentDate: '2026-07-26',
      amountPaid: 420,
      paymentMethod: 'Cash',
      note: 'کاش',
    },
    'sf-113/pay-1': {
      id: 'pay-1',
      formId: 'sf-113',
      paymentDate: '2026-07-15',
      amountPaid: 1200,
      paymentMethod: 'Transfer',
      note: 'حەواڵەی تەواو',
    },
    'sf-114/pay-1': {
      id: 'pay-1',
      formId: 'sf-114',
      paymentDate: '2026-06-25',
      amountPaid: 680,
      paymentMethod: 'Cash',
      note: 'کاش',
    },
    'sf-115/pay-1': {
      id: 'pay-1',
      formId: 'sf-115',
      paymentDate: '2026-06-10',
      amountPaid: 850,
      paymentMethod: 'Cash',
      note: 'کاش',
    },
  },

  buying_forms: {
    'bf-201': {
      id: 'bf-201',
      formNumber: 'BF-201',
      supplierId: 'sup-1',
      supplierName: 'بێدئاڕت (BedArt)',
      issueDate: '2026-09-01',
      totalAmount: 3800,
      customsFee: 150,
      notes: 'بارکردنی دۆشەکی ئۆسکار و ئەلیگرۆ بۆ مەخزەن',
    },
    'bf-202': {
      id: 'bf-202',
      formNumber: 'BF-202',
      supplierId: 'sup-2',
      supplierName: 'ئارمیس (Armis)',
      issueDate: '2026-08-15',
      totalAmount: 4200,
      customsFee: 200,
      notes: 'کڕینی دۆشەکی ئیسکەلەید و ئۆپتیمەم',
    },
    'bf-203': {
      id: 'bf-203',
      formNumber: 'BF-203',
      supplierId: 'sup-4',
      supplierName: 'بێد ئاند سلیپ (Bed & Sleep)',
      issueDate: '2026-07-20',
      totalAmount: 5100,
      customsFee: 180,
      notes: 'سێتی تەختی میلۆدی و دایمۆند',
    },
    'bf-204': {
      id: 'bf-204',
      formNumber: 'BF-204',
      supplierId: 'sup-3',
      supplierName: 'ڤیسکۆ تێکس (ViscoTex)',
      issueDate: '2026-06-28',
      totalAmount: 2600,
      customsFee: 100,
      notes: 'سەرینی ڤیسکۆ و دۆشەکی کلاودس',
    },
    'bf-205': {
      id: 'bf-205',
      formNumber: 'BF-205',
      supplierId: 'sup-6',
      supplierName: 'لۆکە هۆم (Loka Home)',
      issueDate: '2026-05-30',
      totalAmount: 1850,
      customsFee: 50,
      notes: 'بەرگی دۆشەکی جۆراوجۆر',
    },
  },

  buying_form_products: {
    'bf-201/p-1': {
      id: 'p-1',
      formId: 'bf-201',
      productId: 'prod-1-wh',
      productName: 'دۆشەکی ئۆسکار١٨٠*٢',
      category: 'Mattress',
      quantity: 15,
      unitPrice: 180,
      lineTotal: 2700,
    },
    'bf-201/p-2': {
      id: 'p-2',
      formId: 'bf-201',
      productId: 'prod-5-wh',
      productName: 'دۆشەکی ئەلیگرۆ١٨٠*٢',
      category: 'Mattress',
      quantity: 7,
      unitPrice: 160,
      lineTotal: 1100,
    },
    'bf-202/p-1': {
      id: 'p-1',
      formId: 'bf-202',
      productId: 'prod-3-wh',
      productName: 'دۆشەکی ئیسکەلەید ١٨٠*٢',
      category: 'Mattress',
      quantity: 15,
      unitPrice: 220,
      lineTotal: 3300,
    },
    'bf-202/p-2': {
      id: 'p-2',
      formId: 'bf-202',
      productId: 'prod-2-wh',
      productName: 'دۆشەکی ئۆپتیمەم ٩٠*١٩٠',
      category: 'Mattress',
      quantity: 9,
      unitPrice: 95,
      lineTotal: 855,
    },
    'bf-203/p-1': {
      id: 'p-1',
      formId: 'bf-203',
      productId: 'prod-8-wh',
      productName: 'سێتی تەختی میلۆدی 180*2',
      category: 'Bed',
      quantity: 7,
      unitPrice: 450,
      lineTotal: 3150,
    },
    'bf-203/p-2': {
      id: 'p-2',
      formId: 'bf-203',
      productId: 'prod-9-wh',
      productName: 'سێتی تەختی دایمۆند 180*2',
      category: 'Bed',
      quantity: 4,
      unitPrice: 520,
      lineTotal: 2080,
    },
    'bf-204/p-1': {
      id: 'p-1',
      formId: 'bf-204',
      productId: 'prod-11-wh',
      productName: 'سەرینی پشتی ڤیسکۆ L ٦٠*٣٨*١٠',
      category: 'Pillow',
      quantity: 60,
      unitPrice: 18,
      lineTotal: 1080,
    },
    'bf-204/p-2': {
      id: 'p-2',
      formId: 'bf-204',
      productId: 'prod-6-wh',
      productName: 'دۆشەکی کلاودس ١٨٠*٢',
      category: 'Mattress',
      quantity: 6,
      unitPrice: 250,
      lineTotal: 1500,
    },
    'bf-205/p-1': {
      id: 'p-1',
      formId: 'bf-205',
      productId: 'prod-13-wh',
      productName: 'بەرگی دۆشەکی لۆکە هۆم ١٨٠*٢',
      category: 'Cover',
      quantity: 70,
      unitPrice: 14,
      lineTotal: 980,
    },
    'bf-205/p-2': {
      id: 'p-2',
      formId: 'bf-205',
      productId: 'prod-14-wh',
      productName: 'بەرگی دۆشەکی ئاو نەبڕ ١٦٠*٢',
      category: 'Cover',
      quantity: 50,
      unitPrice: 16,
      lineTotal: 800,
    },
  },

  expenses: {
    'exp-1': {
      id: 'exp-1',
      name: 'کرێی مەخزەنی سەرەکی (مانگی ٩)',
      category: 'Rent',
      amount: 1100,
      currency: 'USD',
      date: '2026-09-01',
      paidBy: 'Cash',
      notes: 'کرێی مانگانەی کۆگا',
    },
    'exp-2': {
      id: 'exp-2',
      name: 'مووچەی کارمەندانی فرۆشگا و کۆگا (مانگی ٩)',
      category: 'Salary',
      amount: 2500,
      currency: 'USD',
      date: '2026-09-02',
      paidBy: 'Cash',
      notes: 'مووچەی ٤ کارمەند',
    },
    'exp-3': {
      id: 'exp-3',
      name: 'کارەبای مۆلیدەی پیشەسازی',
      category: 'Electricity',
      amount: 320000,
      currency: 'IQD',
      date: '2026-09-05',
      paidBy: 'Cash',
      notes: 'ئەمپێری مۆلیدە',
    },
    'exp-4': {
      id: 'exp-4',
      name: 'ڕیکلام و سپۆنسەری سۆشیاڵ میدیا',
      category: 'Daily',
      amount: 180,
      currency: 'USD',
      date: '2026-09-10',
      paidBy: 'Transfer',
      notes: 'سپۆنسەری فەیسبووک و ئینستاگرام',
    },
    'exp-5': {
      id: 'exp-5',
      name: 'گواستنەوە و گەیاندنی کاڵا بۆ کڕیاران',
      category: 'Transport',
      amount: 150000,
      currency: 'IQD',
      date: '2026-09-14',
      paidBy: 'Cash',
      notes: 'کرێی بارهەڵگر',
    },
    'exp-6': {
      id: 'exp-6',
      name: 'چاککردنەوە و کەلوپەلی پێداویستی کۆگا',
      category: 'Other',
      amount: 65000,
      currency: 'IQD',
      date: '2026-09-19',
      paidBy: 'Cash',
      notes: 'چاککردنی ڕۆشنایی و دەرگا',
    },
    'exp-7': {
      id: 'exp-7',
      name: 'خەرجی میوانداری و ئاو و چا',
      category: 'Daily',
      amount: 45000,
      currency: 'IQD',
      date: '2026-09-23',
      paidBy: 'Cash',
      notes: 'میوانداری فرۆشگا',
    },
    'exp-8': {
      id: 'exp-8',
      name: 'کرێی مەخزەنی سەرەکی (مانگی ٨)',
      category: 'Rent',
      amount: 1100,
      currency: 'USD',
      date: '2026-08-01',
      paidBy: 'Cash',
      notes: 'کرێی کۆگا',
    },
    'exp-9': {
      id: 'exp-9',
      name: 'مووچەی کارمەندان (مانگی ٨)',
      category: 'Salary',
      amount: 2500,
      currency: 'USD',
      date: '2026-08-02',
      paidBy: 'Cash',
      notes: 'مووچە',
    },
    'exp-10': {
      id: 'exp-10',
      name: 'کارەبای مۆلیدە (مانگی ٨)',
      category: 'Electricity',
      amount: 300000,
      currency: 'IQD',
      date: '2026-08-06',
      paidBy: 'Cash',
      notes: 'کارەبا',
    },
    'exp-11': {
      id: 'exp-11',
      name: 'ڕیکلامی فەیسبووک (مانگی ٨)',
      category: 'Daily',
      amount: 200,
      currency: 'USD',
      date: '2026-08-12',
      paidBy: 'Transfer',
      notes: 'سپۆنسەر',
    },
    'exp-12': {
      id: 'exp-12',
      name: 'گواستنەوەی کاڵا (مانگی ٨)',
      category: 'Transport',
      amount: 175000,
      currency: 'IQD',
      date: '2026-08-18',
      paidBy: 'Cash',
      notes: 'کرێی بارهەڵگر',
    },
    'exp-13': {
      id: 'exp-13',
      name: 'کرێی مەخزەن (مانگی ٧)',
      category: 'Rent',
      amount: 1100,
      currency: 'USD',
      date: '2026-07-01',
      paidBy: 'Cash',
    },
    'exp-14': {
      id: 'exp-14',
      name: 'مووچەی کارمەندان (مانگی ٧)',
      category: 'Salary',
      amount: 2500,
      currency: 'USD',
      date: '2026-07-02',
      paidBy: 'Cash',
    },
    'exp-15': {
      id: 'exp-15',
      name: 'کارەبای مۆلیدە (مانگی ٧)',
      category: 'Electricity',
      amount: 350000,
      currency: 'IQD',
      date: '2026-07-05',
      paidBy: 'Cash',
    },
    'exp-16': {
      id: 'exp-16',
      name: 'کرێی مەخزەن (مانگی ٦)',
      category: 'Rent',
      amount: 1100,
      currency: 'USD',
      date: '2026-06-01',
      paidBy: 'Cash',
    },
    'exp-17': {
      id: 'exp-17',
      name: 'مووچەی کارمەندان (مانگی ٦)',
      category: 'Salary',
      amount: 2500,
      currency: 'USD',
      date: '2026-06-02',
      paidBy: 'Cash',
    },
  },

  stock_movements: {
    'sm-1': {
      id: 'sm-1',
      productId: 'prod-1-wh',
      productName: 'دۆشەکی ئۆسکار١٨٠*٢',
      fromLocation: 'Warehouse',
      toLocation: 'Shop Showroom',
      quantity: 3,
      date: '2026-09-20',
      performedBy: 'پیشاندەر (Demo Admin)',
    },
    'sm-2': {
      id: 'sm-2',
      productId: 'prod-3-wh',
      productName: 'دۆشەکی ئیسکەلەید ١٨٠*٢',
      fromLocation: 'Warehouse',
      toLocation: 'Shop Showroom',
      quantity: 2,
      date: '2026-09-17',
      performedBy: 'پیشاندەر (Demo Admin)',
    },
    'sm-3': {
      id: 'sm-3',
      productId: 'prod-8-wh',
      productName: 'سێتی تەختی میلۆدی 180*2',
      fromLocation: 'Warehouse',
      toLocation: 'Shop Showroom',
      quantity: 1,
      date: '2026-09-12',
      performedBy: 'پیشاندەر (Demo Admin)',
    },
    'sm-4': {
      id: 'sm-4',
      productId: 'prod-11-wh',
      productName: 'سەرینی پشتی ڤیسکۆ L ٦٠*٣٨*١٠',
      fromLocation: 'Warehouse',
      toLocation: 'Shop Showroom',
      quantity: 10,
      date: '2026-09-05',
      performedBy: 'پیشاندەر (Demo Admin)',
    },
  },

  app_settings: {
    companyInfo: {
      id: 'companyInfo',
      name: 'کۆمپانیای بێدئاڕت بۆ کەلوپەلی نووستن - BedArt CRM',
      phone: '0770 307 1818',
      address: 'سلێمانی - شەقامی بازنەیی مەلیک مەحمود',
      currency: 'USD',
      exchangeRate: 1500,
    },
  },
};
